test(swc-angular-preset): ✅ fix nx plugin conflict
Error: Options did not match schema
Cf. https://github.com/jscutlery/devkit/actions/runs/8608266718/job/23590318130